title: Honzův kód
email: honza@honzuvkod.dev
description: >- # this means to ignore newlines until "baseurl:"
  Blog, do kterého si píšu, co za šílenosti právě dělám
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://honzuvkod.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed

